name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v4
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unity-version: 2022.3.29f1
          download-unity-editor: true
          cache-unity-editor: true
          cache-unity-projects: true

      - name: Build Android project
        run: |
          cd .
          ./Unity -batchmode -quit -executeMethod BuildAndroid
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android Build
          path: UnityProject/Builds/Android